name: Bi-hourly Cron

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 15.2
        uses: actions/setup-node@v1
        with:
          node-version: 15.2
      - name: Install dependencies
        run: npm install
      - name: Start
        env:
          CONSUMER_KEY: ${{ secrets.TwitterConsumerKey }}
          CONSUMER_SECRET: ${{ secrets.TwitterConsumerSecret }}
          ACCESS_TOKEN_KEY: ${{ secrets.TwitterAccessTokenKey }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TwitterAccessTokenSecret }}
        run: npm run start:prod
